version: "3"
services:
  mongo:
    image: mongo:4.2.5
    # this is for debugging. i have a firewall (ufw) blocking this from public access
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: webcrawlers
      MONGO_INITDB_ROOT_PASSWORD: blah
    volumes:
      - mongo-vol:/data/db

  ws:
    build:
      context: .
      dockerfile: Dockerfile.ws
    ports:
      - 3001:3001
    env_file:
      - .env.docker
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
      args:
        - NEXT_PUBLIC_WS_PUBLIC_URL=https://localhost
        - NEXT_PUBLIC_API_URL=https://localhost
    env_file:
      - .env.docker

  caddy:
    image: iarekylew00t/caddy-cloudflare:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN}
    restart: unless-stopped
    depends_on:
      - api
      - ws

volumes:
  mongo-vol:
  caddy_data:
  caddy_config:
